sequenceDiagram
participant browser
participant server

browser->>server: GET /spa.html
activate server
server-->>browser: HTML-code
deactivate server
browser->>server: GET /main.css
activate server
server-->>browser: main.css
deactivate server
browser->>server: GET /spa.js
activate server
server-->>browser: spa.js
deactivate server
Note right of browser: browser starts executing js-code that requests JSON data from server
browser->>server: GET /data.json
activate server
server-->>browser: [{content: "..",date: "2033-02-23"}]
deactivate server
Note left of browser: browser executes the event handler that renders notes to display





