sequenceDiagram
participant browser
participant server

Note right of browser: Browser executes the event handler when the submit button is clicked,creating a new note and adding it to the notes list. After that it rerenders the note list on the page and sends the new note to server
browser->>server: POST /new-note-spa
Note left of server: The POST request to the address new-note-spa contains the new note as json data
activate server
server-->>browser: Server responds with status 201 created
deactivate server
Note right of browser: Browser does NOT reload and stays on the same page